# ──────────────────────────────────────────────────────────────
[workspace]
resolver = "2"

[package]
name = "open-dj"
version = "0.1.0"
edition = "2024"
description = "A Tauri App"
authors = ["collinmurch"]

[lib]
name = "open_dj_lib"
path = "src/lib.rs"
crate-type = ["rlib", "cdylib", "staticlib"]

# ── core ──────────────────────────────────────────────────────
[dependencies.tauri]
version = "2.5.1"
default-features = false
features = ["wry"]

[build-dependencies.tauri-build]
version = "2.2"
default-features = false
features = []

# ── plugins ───────────────────────────────────────────────────
[dependencies.tauri-plugin-opener]
version = "2.2"
default-features = false

[dependencies.tauri-plugin-dialog]
version = "2.2"
default-features = false

[dependencies.tauri-plugin-fs]
version = "2.2"
default-features = false

# ── audio ─────────────────────────────────────────────────────
[dependencies.symphonia]
version = "0.5.4"
default-features = false
features = ["wav", "mp3"]

# ── misc ──────────────────────────────────────────────────────
[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
rustfft = "6.2"
rayon = "1.10"
num = "0.4"
rodio = { version = "0.20.1", features = ["symphonia-wav", "symphonia-mp3"] }
lazy_static = "1.5"
env_logger = "0.11"
tokio = { version = "1", features = ["full"] }
biquad = "0.4"
thiserror = "1.0"

[profile.dev]
opt-level = 1
