# ──────────────────────────────────────────────────────────────
[workspace]
resolver = "2" # prevents transitive default-feature creep

[package]
name = "open-dj"
version = "0.1.0"
edition = "2024"
description = "A Tauri App"
authors = ["you"]

[lib]
name = "open_dj_lib"
path = "src/lib.rs"
crate-type = ["rlib", "cdylib", "staticlib"]

# ── core ──────────────────────────────────────────────────────
[dependencies.tauri]
version = "2.5.1"
default-features = false
features = ["wry"]

# `tauri-build` is still at 2.2.x on crates.io
[build-dependencies.tauri-build]
version = "2.2"
default-features = false
features = []

# ── plugins ───────────────────────────────────────────────────
[dependencies.tauri-plugin-opener]
version = "2.2"
default-features = false

[dependencies.tauri-plugin-dialog]
version = "2.2"
default-features = false

[dependencies.tauri-plugin-fs]
version = "2.2"
default-features = false

# ── audio ─────────────────────────────────────────────────────
[dependencies.symphonia]
version = "0.5.4"
default-features = false
features = [
    # containers
    "wav",
    "ogg",
    "isomp4",
    # codecs
    "mp3",
    "vorbis",
    "aac",
    "flac",
]

# ── misc ──────────────────────────────────────────────────────
[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"

[profile.dev]
opt-level = 1
